### ISSUE TITLE
SVGs don't obey dark mode

### ISSUE THREAD

**Issue by surak** [gradio-app/gradio#10482]
- [x I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have been trying to keep the usability of my pages, and I have noticed that the use of dark/light mode of my users is very mixed. So, I try to keep things as neutral as possible. However, SVGs loaded on gradio's pages do not invert color when the rest of the page does. I am talking about headers of my page, not of some gr.Image() output of a model.

**Describe the solution you'd like**  
I'm pretty sure that there's a way to describe, either on the `<img>` or `<svg>` tag, if there's a way to make sure that svgs also get updated when the page changes.

I have an SVG which happens to work just fine like that, as it has this on the svg definition itself:

```css
    <style>
      .cls-1 {
        fill: #ffefbf;
      }
      /* Dark mode: invert SVG colors */
      @media (prefers-color-scheme: dark) {
        svg {
          filter: invert(1);
        }
      }
    </style>
```

I also tried having a 

```
svg { fill=currentColor }
```

On the css of the page being generated. No dice, either.

but if I do it on gradio, with something like `gr.HTML` and the `<img src="blabla.svg">` tag, this goes ignored.

It's probably my lack of knowledge here, but the documentation is not clear on this at all.
