### ISSUE TITLE
Remove scrollers in dataframe

### ISSUE THREAD

**Issue by angelica-ignateva** [gradio-app/gradio#10752]
hey all,

trying to remove scrollers from the data frame. Is they a way?

![Image](https://github.com/user-attachments/assets/b04ad11c-caf1-4005-b9bf-4114c1ac2893)

seems they're displaying by default. tried css, styling, max_height... all didn't work out

**Comment by abidlabs** [comment]
Hmm I can't repro, but it may be your OS settings, can you try OS-specific instructions to hide scrollbars? For example, if you are on a Mac, https://discussions.apple.com/thread/3882122?sortBy=rank

**Comment by angelica-ignateva** [comment]
and if i'm on windows?

**Comment by abidlabs** [comment]
Try this maybe? https://www.tenforums.com/tutorials/103061-turn-off-automatically-hide-scroll-bars-windows-10-uwp-apps.html

**Comment by angelica-ignateva** [comment]
not working, still having scrollers

![Image](https://github.com/user-attachments/assets/e3f0432e-c621-4e08-b4c9-fca690a9449b)

![Image](https://github.com/user-attachments/assets/b8bc3438-de50-4ba9-b174-1ca92fd77893)

**Comment by abidlabs** [comment]
This is happening for all dataframe-related demos? E.g. do you see scrollbars when you open this Space: https://huggingface.co/spaces/gradio/matrix_transpose?

This is what I see:

<img width="1264" alt="Image" src="https://github.com/user-attachments/assets/4ccd66cb-5b2f-4968-b98c-7a7eb647ddad" />

**Comment by angelica-ignateva** [comment]
yep, i see the scrollbars

![Image](https://github.com/user-attachments/assets/0b46e950-ba72-48c2-b920-ddb7299f2855)

seems it's something from windows, as changing the browser doesn't help

according the link you sent, tried to turn off the "always show scrollbars" toggle here, didn't work out

![Image](https://github.com/user-attachments/assets/9418e1cf-a5a0-4b94-852b-2c182b68ec24)

and went to registry editor, but there is no "DynamicScrollbars" folder...

![Image](https://github.com/user-attachments/assets/82e1339a-7b96-467a-9cf9-e77f7d33101d)

**Comment by abidlabs** [comment]
Yeah that's weird, we'll see if we can reproduce this on a Windows computer.

**Comment by yvrjsharma** [comment]
I can confirm the scrollbars appear on a windows 11 machine with the latest gradio sdk `5.20.1`.

Code:
```python
import numpy as np
import gradio as gr

def transpose(matrix):
    return matrix.T

demo = gr.Interface(
    transpose,
    gr.Dataframe(type="numpy", datatype="number", row_count=5, col_count=3, show_fullscreen_button=True),
    "numpy",
    examples=[
        [np.zeros((3, 3)).tolist()],
        [np.ones((2, 2)).tolist()],
        [np.random.randint(0, 10, (3, 10)).tolist()],
        [np.random.randint(0, 10, (10, 3)).tolist()],
        [np.random.randint(0, 10, (10, 10)).tolist()],
    ],
    cache_examples=False
)
demo.launch()
```

However, I can remove these scrollbars using this CSS. Please note that this CSS is sourced from Claude:
```css
# More comprehensive CSS to remove all scrollbars
custom_css = """
/* Hide scrollbars for Chrome, Safari and Opera */
.gradio-container *::-webkit-scrollbar {
  display: none !important;
  width: 0 !important;
  height: 0 !important;
}

/* Hide scrollbars for IE, Edge and Firefox */
.gradio-container * {
  -ms-overflow-style: none !important;  /* IE and Edge */
  scrollbar-width: none !important;  /* Firefox */
}

/* Fix potential overflow issues while ensuring content is still accessible */
.gradio-container [data-testid="table"] {
  overflow: hidden !important;
}

.gradio-container .gradio-dataframe {
  overflow: hidden !important;
}

/* Target additional selectors that might contain scrollbars */
.gradio-container .table-wrap {
  overflow: hidden !important;
}

.gradio-container .scroll-container {
  overflow: hidden !important;
}

/* Handle any fixed height elements that might trigger scrollbars */
.gradio-container .fixed-height {
  max-height: none !important;
}
"""
```
Before applying css:
![Image](https://github.com/user-attachments/assets/a8752c23-52ea-4ab9-9443-5ffe1bc3cbfc)

After applying css:
![Image](https://github.com/user-attachments/assets/ccc84acd-86d9-4d9d-8fa5-7c1913bed06a)
