### ISSUE TITLE
List pnpm version 6 as a requirement in the contributing guide

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1084]
The contributing guide only lists python and npm as dependencies:

![image](https://user-images.githubusercontent.com/41651716/165182977-0ed5553e-3686-4fbd-a30e-d9ca75255801.png)

However, the `build_frontend` script failed because pnmp was not installed. I installed it following the guide here:  https://pnpm.io/installation which defaults to installing version 7 of pnpm but the `build_frontend` script got stuck forever. After looking at the ui.yml github action, I realized the CI installs version 6 of pnpm

```
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
```

so that's what I did locally and then the `build_frontend` script passed!

I'm not sure if anyone else has come across the build failing but I think we should update the contributing guide to mention pnpm version 6 as a requirement so that local environments match ci environments (and so that other people don't come across this problem!)
