### ISSUE TITLE
Have a consistent and decided docstring standard

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1913]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I don't like the current docstring status, there are different standards in the codebase and I don't know which standard we're following. 

**Describe the solution you'd like**  
 I suggest we follow Google standard from now on. WDYT? @aliabd @aliabid94 @freddyaboulton @abidlabs 
```
            Args:
                api_name: 
                body: 
                username: 

            Returns:
                response:

```
