### ISSUE TITLE
When deploy on multiple pods in Kubernetes, nginx ingress does return an HttpOnly cookie but it is not used by Gradio

### ISSUE THREAD

**Issue by MrNocTV** [gradio-app/gradio#1982]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Insight:
- We want to support `enable_queue` params.
- The Gradio apps are deployed on a Kubernetes cluster.
- Each deployed app will have its own sqlite db.
- If requests are round robin, then we will have problem.
- To solve this issue, I'm trying to implement sticky session using cookie. So that requests of a session only come to 1 pod.
- I have updated the ingress configuration to return an Http Cookie.
- The app does return a Cookie in the response header
<img width="842" alt="Screen Shot 2022-08-09 at 09 33 24" src="https://user-images.githubusercontent.com/11014873/183550971-ed2adc94-b8b6-44cf-b582-14a869d15cc6.png">

Problem:
- The subsequence calls do not include the Cookie in the request header.
- Requests are routed to different pods.

**Describe the solution you'd like**  
- The Cookie should be used in subsequence calls.

**Additional context**  
- Ingress configuration:
```yaml
"nginx.ingress.kubernetes.io/affinity":               "cookie",
"nginx.ingress.kubernetes.io/session-cookie-name":    "testCookie",
"nginx.ingress.kubernetes.io/session-cookie-expires": "172800",
"nginx.ingress.kubernetes.io/session-cookie-max-age": "172800",
```
- Ref: 
- https://docs.ovh.com/ca/en/kubernetes/sticky-session-nginx-ingress/#:~:text=Sticky%20sessions%20or%20session%20affinity,redirected%20to%20the%20same%20pod.
- https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
