### ISSUE TITLE
Allow `gr.update()` to accept a component's `.style()` parameters? 

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#2395]
In a Blocks example, I need to update the gallery grid size when a slider value changes.

The grid size can be set like this : `gradio.Gallery().style(grid=2)`.

How can i update a value inside .style() with gr.update() ?

```python
nb_img = gr.Slider(1, 4, value = 1, step = 1, label = 'Number of Images')
gallery = gr.Gallery().style(grid=1)
nb_img.change(lambda n: gr.update( ?????????????? ), inputs=nb_img, outputs=gallery)
```

Does it work if i write:
```python
nb_img.change(lambda n: gr.update( ).style(grid=n), nb_img, gallery)
```

**Comment by abidlabs** [comment]
Unfortunately this is not currently possible, but I agree this would be really nice to support. cc @pngwn @aliabid94  

From the backend, it would be pretty straightforward to allow the `.update()` parameter to accep the `style()` kwargs, but I don't know if the frontend would be able to parse it?

**Comment by fffiloni** [comment]
the css rules involved here are :

```css
.grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
}
@media (min-width: 1024px)
.lg\:grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
}
@media (min-width: 768px)
.md\:grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
}
@media (min-width: 640px)
.sm\:grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
}
```
