### ISSUE TITLE
Make it possible to call gradio.Slider.change only when slider is released

### ISSUE THREAD

**Issue by cakiki** [gradio-app/gradio#3204]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For apps without a "run" button logic, updating the slider immediately changes the state of the app, without the opportunity to scroll the slider toward a value of interest.

**Describe the solution you'd like**  
It would be nice if `gradio.Slider.change` could be further customized to only be called when a user lets go of the slider. 

**Additional context**  
NA

**Comment by pngwn** [comment]
Seems reasonable, would it make sense to make this available via some flag to the Slider component or do we think this is just better default behaviour (or both, i guess)?

cc @abidlabs

**Comment by freddyaboulton** [comment]
Can we use the existing `Blur` event here @pngwn ?

**Comment by meg-huggingface** [comment]
+1 on this functionality, thanks!

**Comment by pngwn** [comment]
@freddyaboulton Yeah, we can just emit a new event for it, if `blur` makes sense for the api. Would be a quick one.

**Comment by or25** [comment]
Hi!
since it was an issue with the label "good first contribute" i tried fixing this issue but i've run into some problem - i don't know how to debug the ui :)
I'm making some changes - i think i know where the problem is, but how do i test it?
Running the workbench at ui? the app at the packages folder?
Should i create a new svelte application (never used it, react programmer here), then import my component and see if it works? 

i'd like some advices and insights pls :)

@freddyaboulton or @pngwn, maybe you two will be able to help me!

**Comment by dawoodkhan82** [comment]
@or25 You can test your changes by running a gradio demo from the `gradio/demo` dir. In this case you can test using the `gradio/demo/kitchen_sink/run.py` demo. You must keep this demo running and also at the same time run the frontend in dev mode to debug your frontend changes. Make sure you have the right versions below. Then run `pnpm i` from the `gradio/ui` dir to install all node packages; and finally run `pnpm dev` to run the frontend in dev mode. The app should be running on http://localhost:9876/

> Prequisites:
> 
> [Python 3.7+](https://www.python.org/downloads/)
> [pnpm version 7.x](https://pnpm.io/7.x/installation) (optional for backend-only changes, but needed for any frontend changes)

Hope that helps

**Comment by or25** [comment]
> 

I did'nt get it actually.
If i'm debugging the backend - i'm running the main.py file with the gradio module, then making changes to the gradio module source files.
If i'm debugging the frontend i want to run pnpm at the ui folder. It runs, opening an application at port 3000, which has nothing but a gradio loading icon (as if loading the application).
I don't know how to run the frontend then, i did exactly as you told so, and i don't actually get how running the demo and then running another session of frontend will affect each other.

**Comment by pngwn** [comment]
Did you run a demo and open a new terminal window and run the UI? You need to run both at the same time. Make sure you pull latest `main`, the UI should start on `localhost:9876`.

**Comment by abidlabs** [comment]
Closed via #3353, thanks @freddyaboulton!

**Comment by Nacurutu** [comment]
Using @Gerschel 's extension: https://github.com/Gerschel/sd-web-ui-quickcss and loading Alani or Neon theme, you will have a slider that let you resize the extra networks... 

Also, if you don't want to install the extension, you can create a user.css file and copy this code to it:


```css

:root, * , quickcss_target{
    --cards_size: 50;

}

/* TI - HN - LoRa Cards - Checkpoints*/
/*----------------------------------------------------------------*/
#tabs .tabitem .card{
 width: calc(3px *var(--cards_size));
 height: calc(4.48px *var(--cards_size));
 min-width: 50px !important;
 min-height: 74.6px !important;
 font-size: 60%;
 text-align: center;
 color: var(--Primary_color);
 transition: all 0.1s ease-in-out;
 border-width: 1px;
 border-color: var(--Secondary_color); 
}

#tabs .tabitem .card:hover {
border-width: 3px ;
border-color: var(--Primary_color);
}

/* Extra network cards */
#tabs .tabitem .extra-network-cards{
 display:flex;
 flex-wrap:wrap;
 justify-content:center;
}

/* Cards Animations */

.extra-network-cards .card{

transition-property: transform;
	transition-timing-function: cubic-bezier(.4,0,.2,1);
    transition-duration: .5s;
    transform: rotateX(0) rotateY(12deg);
}
      
    .extra-network-cards .card:hover{
    box-shadow: 0 0 2px 0.3em rgba(0, 128, 255, 0.35);

    transform-style: preserve-3d;
	animation: hovering 5s ease infinite;

    transform-style: preserve-3d;
	animation: hovering 5s ease infinite;
}

@keyframes hovering {
	0% {
		transform: rotateX(0) rotateY(12deg)
	}

	25% {
		transform: rotateX(12deg) rotateY(0)
	}

	50% {
		transform: rotateX(0) rotateY(-12deg)
	}

	75% {
		transform: rotateX(-12deg) rotateY(0)
	}

	to {
		transform: rotateX(0) rotateY(12deg)
	}

  }

```

Where --cards_size: (a number between 50 and 100)


But, I think installing the extension is easier.
