### ISSUE TITLE
Sliders should look consistent in all kinds of web browsers

### ISSUE THREAD

**Issue by Keldos-Li** [gradio-app/gradio#4255]
- [x] I have searched to see if a similar issue already exists.

## Description
I'm a Mac user (and developer). Sliders in safari look really ugly and annoying... What's worse, the variable `color_accent` in theme builder makes no change to sliders in safari.
<img width="551" alt="image" src="https://github.com/gradio-app/gradio/assets/23137268/477c7fc5-650b-40f7-bdb9-6a9f86bd37e6">

In fact, the slider is such an odd html element that varies from browser to browser:
![](https://user-images.githubusercontent.com/23137268/236451494-cf5ab484-4ffb-4922-826a-91b23e28dacd.png)

**It _should_ and _could_ be improved to make a theme prettier and consistent.**

## Solution
In my attempt a few weeks ago, I made sliders look from this
![](https://user-images.githubusercontent.com/23137268/236452538-e4189eff-7c2d-4cf2-b64b-181f0b646054.png)
to this
![](https://user-images.githubusercontent.com/23137268/236452453-37fbd6cd-845f-487f-8176-3146e264f79e.png)
(Firefox, Chrome and Safari in turn)

You can see my original PR and changes [here](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/734). 
(Maybe you can also check the live preview in [this hugging face space](https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT) a few minutes later. This space is outdated for now... I've just asked my teammate to update it).

The main core change in the code is
```css
input[type="range"] {
     -webkit-appearance: none;
     height: 4px;
     background: var(--input-background-fill);
     border-radius: 5px;
     background-image: linear-gradient(var(--primary-500),var(--primary-500));
     background-size: 0% 100%;
     background-repeat: no-repeat;
 }
 input[type="range"]::-webkit-slider-thumb {
     -webkit-appearance: none;
     height: 20px;
     width: 20px;
     border-radius: 50%;
     border: solid 0.5px #ddd;
     background-color: white;
     cursor: ew-resize;
     box-shadow: var(--input-shadow);
     transition: background-color .1s ease;
 }
 input[type="range"]::-webkit-slider-thumb:hover {
     background: var(--neutral-50);
 }
 input[type=range]::-webkit-slider-runnable-track {
     -webkit-appearance: none;
     box-shadow: none;
     border: none;
     background: transparent;
 }
```
```js
 var rangeInputs = null;
 var numberInputs = null;
 function setSlider() {
     rangeInputs = document.querySelectorAll('input[type="range"]');
     numberInputs = document.querySelectorAll('input[type="number"]')
     setSliderRange();
     rangeInputs.forEach(rangeInput => {
         rangeInput.addEventListener('input', setSliderRange);
     });
     numberInputs.forEach(numberInput => {
         numberInput.addEventListener('input', setSliderRange);
     })
 }
 function setSliderRange() {
     var range = document.querySelectorAll('input[type="range"]');
     range.forEach(range => {
         range.style.backgroundSize = (range.value - range.min) / (range.max - range.min) * 100 + '% 100%';
     });
 }
```
*The CSS code changed the style of the slider, and the js code changed the width on the left side of the slider.*

I'm not so familiar with gradio development framework... So I just put my advice here.

**Additional context**  

The method I currently provide is suitable for webkit browsers such as safari, Chrome, edge, while Firefox may need to be written differently. Though sliders look fine even in Firefox after my fix. Read about how Firefox differs from other browsers:
- W3C proposal on slider CSS selector: https://github.com/w3c/csswg-drafts/issues/4410

**Comment by dawoodkhan82** [comment]
@abidlabs @pngwn I've been looking into this and it would take a lot of custom JS and CSS to re-do how each browser styles the slider. I also don't know if it's recommended to re-style native browser components.

**Comment by abidlabs** [comment]
Personally I think its worth it -- sliders look particularly bad in Safari, and if there's any time to redesign our slider, it would be now before the 4.0 release!

**Comment by Keldos-Li** [comment]
I think it is quite common for developers to modify native web components. In fact, you have already modified things like radio and checkbox, right? Although for sliders, it may require more JavaScript to achieve the progress bar effect.

We have been exploring the potential of Gradio, and now we have achieved something like this... All of this comes from our bold attempt to modify the original components you provided... \_(:з」∠)\_ 

[iShot_2023-09-12_下午12.56.23.webm](https://github.com/gradio-app/gradio/assets/23137268/a79c1307-e46e-4c3d-a345-341be4aa0e1a)

**Comment by henryruhs** [comment]
This was indeed a bad idea... see https://github.com/gradio-app/gradio/issues/5803

```css
input[type="range"] {
    height: 4px;
} 
```
