### ISSUE TITLE
How to use Kubernetes to run gradio app

### ISSUE THREAD

**Issue by fly2tomato** [gradio-app/gradio#455]
I want to use Kubernetes to manage my gradio app. But it doesn't work.

Here is my steps:
First of all, create a demo gradio app:
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

def main():
    print("starting gradio")
    gr.Interface(fn=greet, inputs="text", outputs="text", server_name="0.0.0.0", server_port=7601).launch()
    print("gradio started")

if __name__ == '__main__':
    main()
```

Then, containerize it as a docker image:
```
FROM python:3.8
RUN pip install gradio==2.4.6
COPY src /app
WORKDIR /app
EXPOSE 7601
CMD ["python", "app.py"]
```

After that, create a k8s yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-demo-pytorch
  namespace: openmmlab
  labels:
    k8s-app: inference-engine
spec:
  selector:
    matchLabels:
      name: gradio-demo-pytorch
  replicas: 1
  template:
    metadata:
      labels:
        name: gradio-demo-pytorch
    spec:
      restartPolicy: Always
      nodeSelector:
        workfor: inference
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: gradio-demo-pytorch
          image: 10.1.32.6:28080/public/gradio-demo:latest
          ports:
            - containerPort: 7601
              protocol: TCP
          resources:
            limits:
              memory: 10000Mi
            requests:
              memory: 2000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-demo-pytorch
  labels:
    k8s-app: inference-engine
  namespace: openmmlab
spec:
  type: NodePort
  ports:
    - port: 7601
      targetPort: 7601
      nodePort: 30601
  selector:
    k8s-app: inference-engine
```

Lastly, start gradio app in k8s.

A point confused me that, the app can run in docker successfully, like:
```
IMPORTANT: You are using gradio version 2.4.6, however version 2.5.1 is available, please upgrade.
--------
Running on local URL:  http://0.0.0.0:7601/

To create a public link, set `share=True` in `launch()`.
```

But, when using k8s to run this, there is no logs feedback and can't access via browser either.

**Comment by abidlabs** [comment]
I'm not an expert at kubernetes, but I'll ask around. Is there a reason you are using an older version of Gradio? In the latest version, as you may know, `server_name="0.0.0.0", server_port=7601` should go into the `launch()` method

**Comment by fly2tomato** [comment]
> 

Thanks for reminding about the version change. I've updated gradio to the latest version 2.5.1.
I am looking forward to your further information.

**Comment by fly2tomato** [comment]
update by myself
This is a problem relative to the python print cache. Only need to add an env PYTHONUNBUFFERED=1 in the pod should work (for me it works). 
Here is the k8s yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-demo-pytorch
  namespace: openmmlab
  labels:
    k8s-app: inference-engine
spec:
  selector:
    matchLabels:
      name: gradio-demo-pytorch
  replicas: 1
  template:
    metadata:
      labels:
        name: gradio-demo-pytorch
    spec:
      restartPolicy: Always
      nodeSelector:
        workfor: inference
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: gradio-demo-pytorch
          image: 10.1.32.6:28080/public/gradio-demo:latest
          ports:
            - containerPort: 7601
              protocol: TCP
          resources:
            limits:
              memory: 10000Mi
            requests:
              memory: 2000Mi
##### add these bellow ####
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-demo-pytorch
  labels:
    k8s-app: inference-engine
  namespace: openmmlab
spec:
  type: NodePort
  ports:
    - port: 7601
      targetPort: 7601
      nodePort: 30601
  selector:
    k8s-app: inference-engine
```
