### ISSUE TITLE
Slider bar are too thin on FireFox

### ISSUE THREAD

**Issue by henryruhs** [gradio-app/gradio#5803]
### Describe the bug

The slider handles under FireFox are barley clickable using Gradio 3.46.1. In contrast Chroma does have something like a click tolerance around it.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Just use the UI

### Screenshot

Cursor is not visible but I actual clicked 4 to 5 times like 2px next from the slider bar.

[Bildschirmaufzeichnung vom 05.10.2023, 09:09:50.webm](https://github.com/gradio-app/gradio/assets/1835397/6002e47a-0cb8-4aa7-9b53-1a548055516d)

### System Info

```shell
FireFox 118
```

### Severity

Blocking usage of gradio

**Comment by henryruhs** [comment]
I suggest to expose all slider CSS as variables:

```
--slider-handle-radius
--slider-handle-color
--slider-bar-height
--slider-bar-color (instead slider-color)
``

**Comment by abidlabs** [comment]
Is this only an issue on Firefox?

**Comment by henryruhs** [comment]
Yes, it works pretty good with Chroma due the fact that your cursor does not have to click right on the slider bar.

FireFox needs like 6px to 8px slider bar height in order to work acceptable.

**Comment by abidlabs** [comment]
cc @dawoodkhan82 can you take a look?

**Comment by dawoodkhan82** [comment]
Will fix!

**Comment by henryruhs** [comment]
@dawoodkhan82 If you want to keep thin bars the height of `moz-range-track, moz-range-progress` and `webkit-slider-runnable-track,webkit-progress-value` needs to be adjusted and not the whole `input[type="range"]` height due this defines the clickable area.

Just in case you are interested, this is my temp fix with slightly different look:

![grafik](https://github.com/gradio-app/gradio/assets/1835397/b74d55fb-78cd-46b4-b420-b4d459df9f0d)

```css
:root:root:root input[type="range"]
{
	height: 0.5rem;
}

:root:root:root input[type="range"]::-moz-range-thumb,
:root:root:root input[type="range"]::-webkit-slider-thumb
{
	background: var(--neutral-300);
	border: unset;
	box-shadow: unset;
	border-radius: 50%;
	height: 1.125rem;
	width: 1.125rem;
}

:root:root:root input[type="range"]::-webkit-slider-thumb
{
	margin-top: 0.375rem;
}
```

Fixed also the `input[type="number"]` as it let's the label wrap quite often.

```css
:root:root:root input[type="number"]
{
	max-width: 6rem;
}
```
