### ISSUE TITLE
Customize the progress bar

### ISSUE THREAD

**Issue by henryruhs** [gradio-app/gradio#5815]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It would be great to customize the progress bar using CSS variables.

**Describe the solution you'd like**

### Original

![Bildschirmfoto vom 2023-10-05 23-36-01](https://github.com/gradio-app/gradio/assets/1835397/319b066d-131b-420a-91f3-c9351379047f)

### Custom

![Bildschirmfoto vom 2023-10-05 23-48-50](https://github.com/gradio-app/gradio/assets/1835397/ccf872c0-6da1-45ed-b9bf-9137d643f824)

**Additional context**  
CSS I'm using:

```css
.progress-bar-wrap.progress-bar-wrap.progress-bar-wrap
{
	border-radius: var(--input-radius);
	height: 1.25rem;
	margin-top: 1rem;
	overflow: hidden;
	width: 70%;
}
```

Are you open for a pull request? Should be a easy first pick for me.
