### ISSUE TITLE
iOS • CSS • Examples Gallery elements stretched full width

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#7385]
### Describe the bug

Hello ! 

On Safari iOS, the 4.* gradio Examples component gallery displays img elements stretched full-width:
![IMG_1252](https://github.com/gradio-app/gradio/assets/7447007/8ed6d0cf-f64c-4f6c-87ff-e66727b47f7a)

**Temporary fix** with custom CSS in app.py, where "component-11" is the example component div:

```css
/* fix examples gallery width on mobile */

div#component-11 > .gallery > .gallery-item > .container > img {
    width: auto!important;
}
```

Instead of `width: 100%;`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Try the Examples component with several image and open it on iOS Safari

### System Info

```shell
Gradio 4.*
```

### Severity

I can work around it
