### ISSUE TITLE
`gr.Plot` is resized indefinitely when using a custom CSS

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#9068]
### Describe the bug

When I use the following custom CSS to adjust `plotly` graph, the graph will keep expand indefinitely on HF Spaces.
```css
.js-plotly-plot .plotly {
  padding-top: 30px !important;
  background-color: white;
}

.js-plotly-plot .plotly .modebar {
  top: -30px !important;
  right: 10px !important;
}

.modebar-group {
  display: flex;
  flex-direction: row;
  align-items: center;
}
```
This was working as expected before `gradio==4.37.x`.

(I reported this internally last month, but apparently I didn't open an issue and it's been forgotten. [internal slack](https://huggingface.slack.com/archives/C02QZLG8GMN/p1720340294704409))

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

repro: https://huggingface.co/spaces/hysts-debug/plotly-custom-css

```python
import gradio as gr
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(0)
data = np.random.normal(size=(1000, 3))
data[0, :] = 0
data = data.cumsum(axis=0)
df = pd.DataFrame(data, columns=["a", "b", "c"])

with gr.Blocks(css="style.css") as demo:
    for _ in range(3):
        gr.Plot(value=px.line(df))

if __name__ == "__main__":
    demo.queue().launch()
```

```css
.js-plotly-plot .plotly {
  padding-top: 30px !important;
  background-color: white;
}

.js-plotly-plot .plotly .modebar {
  top: -30px !important;
  right: 10px !important;
}

.modebar-group {
  display: flex;
  flex-direction: row;
  align-items: center;
}
```

### Screenshot

https://github.com/user-attachments/assets/1f777d82-9ce1-4653-b7b0-bfd10993d32c

### System Info

```shell
gradio==4.40.0
```

### Severity

Blocking usage of gradio
