### ISSUE TITLE
CSS preload error with custom root_path

### ISSUE THREAD

**Issue by cornzz** [gradio-app/gradio#9101]
### Describe the bug
**TLDR:** Two bugs occur when setting a custom root_path:
1. `global.css` is being preloaded with the wrong base url in `mountCss()`. Fix: use something like `window.location.href` as base url?
2. Favicon is broken. Fix: add `<link rel="icon" href="favicon.ico">` to html head?

---

This is not a big problem, I just noticed that my gradio app, which runs behind a reverse proxy on the path `/app`, is throwing this error in the browser console
```
Unable to preload CSS for https://example.com/assets/index-BG5BHdVr.css                  css.ts:28
```
The css file in question is the [`global.css`](https://github.com/gradio-app/gradio/blob/main/js/theme/src/global.css) file which is bundled and included in `gradio/templates/frontend/index.html` with a relative path:
```html
<link rel="stylesheet" crossorigin href="./assets/index-BG5BHdVr.css">
```
Since it is a relative path here, the app works fine and the css is loaded normally from `/app/assets`, its just that this [css preloading function](https://github.com/gradio-app/gradio/blob/main/js/core/src/css.ts#L15) does not take into account the custom root path, instead it uses `new URL(import.meta.url).origin` as the base to get the full URL for the css file in question.

Also slightly related, the browser cannot find a favicon at the root `/`, so it does not display any favicon. The fix is simple, add a relative favicon link to the template head, i.e. `<link rel="icon" href="favicon.ico">`.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

`app.py`:
```python
APP_PATH = "/app"
app = FastAPI(root_path=APP_PATH)
...
app = gr.mount_gradio_app(app, demo, path="/", root_path=APP_PATH)
```

<details>
<summary>Kubernetes ingress:</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.com
    secretName: example.com-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: demo-service
            port:
              number: 80
```

</details>

### Screenshot

<img width="878" alt="Screenshot 2024-08-13 at 19 50 19" src="https://github.com/user-attachments/assets/d2e89d89-2ad9-4984-a5e5-17dbbd31190d">

### System Info
<details>

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.40.0
gradio_client version: 1.2.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.112.0
ffmpy: 0.4.0
gradio-client==1.2.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.24.5
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.0
numpy: 1.26.4
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.6
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.5
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.

gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.24.5
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

</details>

### Severity

I can work around it
