### ISSUE TITLE
Copy button in 5.0.0b7 Textbox is misplaced/invisible

### ISSUE THREAD

**Issue by CISC** [gradio-app/gradio#9569]
### Describe the bug

Enabling `show_copy_button` on a `Textbox` appears to do nothing, upon closer inspection it seems to be misplaced inside the `textarea` instead of in the outter container.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Textbox("Rendered Template", label="Chat Prompt", show_copy_button=True)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/29bcadf3-2e9a-4c8d-b589-438dea7ceb22)
![image](https://github.com/user-attachments/assets/5165e08e-a959-4a10-ba6b-2d0b98c1dfa1)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.0.0b7
gradio_client version: 1.4.0b3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.0
fastapi: 0.115.0
ffmpy: 0.4.0
gradio-client==1.4.0-beta.3 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.0
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.2
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.12
pyyaml: 6.0.2
ruff: 0.6.9
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.31.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.25.0
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by Dnyanu76** [comment]
i can fix this problem

**Comment by pngwn** [comment]
Can we check if this is still broken in the new 5.x release?

**Comment by JerryKwan** [comment]
I am using version 5.0.2, show_copy_button does't work as expected.

**Comment by JerryKwan** [comment]
one temporary fix is adding z-index: 999; to .copy-button, such as the following 
```css
.copy-button {
		display: flex;
		position: absolute;
		top: var(--block-label-margin);
		right: var(--block-label-margin);
		align-items: center;
		box-shadow: var(--shadow-drop);
		border: 1px solid var(--color-border-primary);
		border-top: none;
		border-right: none;
		border-radius: var(--block-label-right-radius);
		background: var(--block-label-background-fill);
		padding: 5px;
		width: 22px;
		height: 22px;
		overflow: hidden;
		color: var(--block-label-color);
		font: var(--font-sans);
		font-size: var(--button-small-text-size);
		z-index: 999;
	}
```
